version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: books_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booksdb
    volumes:
      - books_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./book-crud-backend
    container_name: nest_books_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: booksdb
    command: npm run start:dev

  frontend:
    build:
      context: ./book-crud-frontend
    container_name: next_books_frontend
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/usr/src/app 
      - /usr/src/app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  books_data:
